# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_usernormal_interested_tags'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='user.UserNormal'),
        ),
    ]
