# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_auto_20181018_0946'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('text', models.TextField(verbose_name='Tartisma Metni')),
                ('pageview', models.PositiveIntegerField(default=0)),
                ('video_url', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserNormal')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='discussion_dislike_list', to='user.UserNormal')),
                ('likes', models.ManyToManyField(blank=True, related_name='discussion_like_list', to='user.UserNormal')),
                ('tags', models.ManyToManyField(blank=True, to='tag.Tag')),
            ],
        ),
    ]
