# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181018_0946'),
        ('discussion', '0002_auto_20181213_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discuss_comments', to='user.UserNormal')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='discussion.Discusion')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disc_comment_dislike_list', to='user.UserNormal')),
                ('likes', models.ManyToManyField(blank=True, related_name='disc_comment_like_list', to='user.UserNormal')),
            ],
        ),
    ]
