# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_discussioncomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discusion',
            new_name='Discussion',
        ),
    ]
