# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181018_0946'),
        ('discussion', '0004_auto_20181219_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserNormal')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disc_reply_dislike_list', to='user.UserNormal')),
                ('likes', models.ManyToManyField(blank=True, related_name='disc_reply_like_list', to='user.UserNormal')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussion.Discussion')),
            ],
        ),
    ]
