# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_discussionreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionreply',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussion.DiscussionComment'),
        ),
    ]
