# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_auto_20181221_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='user.UserNormal'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='discussion', to='tag.Tag'),
        ),
    ]
