# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-16 13:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20180729_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='', verbose_name='Resim')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('pageview', models.IntegerField(verbose_name='Görüntülenme Sayısı')),
                ('tags', models.TextField()),
                ('is_active', models.BooleanField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserNormal')),
            ],
        ),
    ]
