# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180819_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statictics',
            new_name='ArticleStatictics',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tag.Tag'),
            preserve_default=False,
        ),
    ]
