# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180910_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Yayınla'),
        ),
        migrations.AlterField(
            model_name='article',
            name='statistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleStatictics'),
        ),
    ]
