# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180926_1915'),
        ('article', '0005_auto_20180912_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='statistics',
        ),
        migrations.AddField(
            model_name='article',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='article_dislike_list', to='user.UserNormal'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='article_like_list', to='user.UserNormal'),
        ),
        migrations.AddField(
            model_name='article',
            name='pageview',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.Tag'),
        ),
        migrations.DeleteModel(
            name='ArticleStatictics',
        ),
    ]
