# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180926_1915'),
        ('article', '0006_auto_20181002_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('is_positive', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='article.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='user.UserNormal')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='comment_dislike_list', to='user.UserNormal')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_like_list', to='user.UserNormal')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserNormal')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='reply_dislike_list', to='user.UserNormal')),
                ('likes', models.ManyToManyField(blank=True, related_name='reply_like_list', to='user.UserNormal')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Comment')),
            ],
        ),
    ]
