# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20181004_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_positive',
            field=models.BooleanField(default=True),
        ),
    ]
