# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_relatedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedarticle',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
