# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_relatedarticle_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='relatedarticle',
            name='author',
        ),
        migrations.DeleteModel(
            name='RelatedArticle',
        ),
    ]
