# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-29 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernormal',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkımda'),
        ),
        migrations.AlterField(
            model_name='usernormal',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Doğum Günü'),
        ),
        migrations.AlterField(
            model_name='usernormal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil Fotoğrafı'),
        ),
    ]
