# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-29 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180729_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernormal',
            name='gender',
            field=models.BinaryField(verbose_name='Cinsiyet'),
        ),
    ]
