# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-31 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('user', '0003_auto_20180729_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('follower_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='usernormal',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
        migrations.AddField(
            model_name='usernormal',
            name='followers',
            field=models.ManyToManyField(related_name='_usernormal_followers_+', to='user.UserNormal'),
        ),
        migrations.AddField(
            model_name='usernormal',
            name='following',
            field=models.ManyToManyField(related_name='_usernormal_following_+', to='user.UserNormal'),
        ),
        migrations.AddField(
            model_name='usernormal',
            name='interested_tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='usernormal',
            name='language_choice',
            field=models.CharField(default='TR', max_length=5),
        ),
        migrations.AddField(
            model_name='usernormal',
            name='statistics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserStatistics'),
        ),
    ]
