# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-31 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180831_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernormal',
            name='interested_tags',
            field=models.ManyToManyField(related_name='user', to='tag.Tag'),
        ),
    ]
