# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180926_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernormal',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_usernormal_followers_+', to='user.UserNormal'),
        ),
        migrations.AlterField(
            model_name='usernormal',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_usernormal_following_+', to='user.UserNormal'),
        ),
        migrations.AlterField(
            model_name='usernormal',
            name='interested_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='usernormal',
            name='statistics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserStatistics'),
        ),
    ]
