# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_remove_tag_followers'),
        ('user', '0008_remove_usernormal_interested_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernormal',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='tag.Tag'),
        ),
    ]
